@extends('admin.pages.master')
@section('title','Promotions')
@section('content')
<div class="container-fluid"><div class="page-title-box"><h4>Promotional Codes & Campaigns</h4><p class="text-muted mb-0">Manage campaign eligibility and link App Store subscription benefits to Apple's supported offer identifiers. This module does not bypass App Store billing.</p></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="row"><div class="col-xl-5"><div class="card"><div class="card-header"><h5 class="mb-0">Create promotion</h5></div><div class="card-body"><form method="post" action="{{ route('admin.promotions.store') }}">@csrf
<div class="mb-3"><label class="form-label">Campaign name</label><input name="name" class="form-control" required></div><div class="row"><div class="col-md-6 mb-3"><label>Code</label><input name="code" class="form-control"></div><div class="col-md-6 mb-3"><label>Apple offer identifier</label><input name="apple_offer_identifier" class="form-control"></div></div>
<div class="mb-3"><label>Eligible plans</label><select name="eligible_plans[]" multiple class="form-select"><option value="free">Free</option><option value="tasks">Tasks</option><option value="renewals">Renewals</option><option value="essentials">Essential</option><option value="documents">Document Locker</option><option value="complete">Complete</option></select></div>
<div class="mb-3"><label>Benefit / admin note</label><input name="benefit" class="form-control" placeholder="e.g. 1 month promotional offer"></div><div class="row"><div class="col-md-6 mb-3"><label>Eligibility</label><select name="eligibility" class="form-select"><option>all</option><option>free</option><option>trial</option><option>paid</option></select></div><div class="col-md-6 mb-3"><label>Usage limit</label><input type="number" min="1" name="usage_limit" class="form-control"></div></div>
<div class="row"><div class="col-md-6 mb-3"><label>Starts</label><input type="datetime-local" name="starts_at" class="form-control"></div><div class="col-md-6 mb-3"><label>Ends</label><input type="datetime-local" name="ends_at" class="form-control"></div></div><div class="form-check mb-3"><input class="form-check-input" type="checkbox" name="is_active" value="1" id="active"><label class="form-check-label" for="active">Active</label></div><button class="btn btn-primary">Create campaign</button></form></div></div></div>
<div class="col-xl-7"><div class="card"><div class="card-header"><h5 class="mb-0">Campaigns</h5></div><div class="card-body table-responsive"><table class="table align-middle"><thead><tr><th>Campaign</th><th>Eligibility</th><th>Usage</th><th>Dates</th><th>Status</th><th></th></tr></thead><tbody>@forelse($promotions as $p)<tr><td><strong>{{ $p->name }}</strong><br><small>{{ $p->code ?: 'No public code' }}{{ $p->apple_offer_identifier ? ' · Apple: '.$p->apple_offer_identifier : '' }}</small></td><td>{{ ucfirst($p->eligibility) }}</td><td>{{ $p->redemptions_count }} / {{ $p->usage_limit ?: '∞' }}</td><td><small>{{ optional($p->starts_at)->format('d M Y') ?: 'Now' }} → {{ optional($p->ends_at)->format('d M Y') ?: 'Open' }}</small></td><td><span class="badge bg-soft-{{ $p->is_active?'success':'secondary' }} text-{{ $p->is_active?'success':'secondary' }}">{{ $p->is_active?'Active':'Inactive' }}</span></td><td><form method="post" action="{{ route('admin.promotions.toggle',$p) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-light">Toggle</button></form></td></tr>@empty<tr><td colspan="6" class="text-muted">No promotions yet.</td></tr>@endforelse</tbody></table></div></div></div></div></div>
@endsection
